# .github\workflows\release.yml
name: Build and Release (Windows + Linux + macOS Standalone)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.compare.outputs.greater }}
      version: ${{ steps.read_version.outputs.version }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get latest release tag
        id: latest
        env:
          TOKEN: ${{ github.token }}
        run: |
          set -e
          LATEST_TAG=$(curl -s -H "Authorization: token ${TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name // empty')
          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then LATEST_TAG="0.0.0"; fi
          LATEST_VERSION=$(printf "%s" "$LATEST_TAG" | sed -E 's/^[^0-9]*//')
          echo "LATEST_TAG=$LATEST_TAG"           >> $GITHUB_ENV
          echo "LATEST_VERSION=$LATEST_VERSION"   >> $GITHUB_ENV
          echo "LATEST_VERSION=$LATEST_VERSION"

      - name: Read version.txt
        id: read_version
        run: |
          set -e
          [ -f version.txt ] || { echo "version.txt introuvable à la racine"; exit 1; }
          RAW_VERSION=$(head -n1 version.txt | tr -d '\r' | xargs)
          [ -n "$RAW_VERSION" ] || { echo "version.txt est vide"; exit 1; }
          VERSION=$(printf "%s" "$RAW_VERSION" | sed -E 's/^[^0-9]*//')
          echo "VERSION=$VERSION"         >> $GITHUB_ENV
          echo "version=$VERSION"         >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"

      - name: Compare versions
        id: compare
        run: |
          echo "Comparaison: NEW=${{ env.VERSION }} ; LATEST=${{ env.LATEST_VERSION }}"
          if dpkg --compare-versions "${{ env.VERSION }}" gt "${{ env.LATEST_VERSION }}"; then
            echo "greater=true"  >> $GITHUB_OUTPUT
            echo "GREATER=true"  >> $GITHUB_ENV
            echo "Nouvelle version détectée"
          else
            echo "greater=false" >> $GITHUB_OUTPUT
            echo "GREATER=false" >> $GITHUB_ENV
            echo "Pas de bump de version"
          fi

      - name: Compute tag
        id: tag
        run: |
          echo "tag=v${{ env.VERSION }}" >> $GITHUB_OUTPUT

  Windows_Standalone_Build:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: windows-2022
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps (PyInstaller + project)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { python -m pip install -r requirements.txt }
          python -m pip install "pyinstaller>=6.0"
          pyinstaller --version

      - name: Create entrypoint (GUI only)
        shell: pwsh
        run: |
          Set-Content entry_gui.py @"
          from scanner.gui import launch_gui
          if __name__ == "__main__":
              launch_gui()
          "@

      - name: Prepare Windows resources from templates
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "build-res" | Out-Null
          $ver = "${{ needs.build.outputs.version }}"; if ([string]::IsNullOrWhiteSpace($ver)) { $ver = "0.0.0" }

          if (!(Test-Path "scanner/packaging/win/file_version.txt.tmpl")) {
            Write-Error "Template manquant: scanner/packaging/win/file_version.txt.tmpl"; exit 1
          }
          if (!(Test-Path "scanner/packaging/win/app.manifest")) {
            Write-Error "Manifest manquant: scanner/packaging/win/app.manifest"; exit 1
          }

          # Substitution des tokens dans le version-file
          $tmpl = Get-Content "scanner/packaging/win/file_version.txt.tmpl" -Raw -Encoding UTF8
          $tmpl = $tmpl -replace '\{\{VER\}\}', ($ver -replace '\.', ', ')
          $tmpl = $tmpl -replace '\{\{VERSTR\}\}', $ver
          Set-Content -Path "build-res\file_version.txt" -Value $tmpl -Encoding UTF8

          # Copie du manifest
          Copy-Item "scanner/packaging/win/app.manifest" "build-res/app.manifest" -Force

      - name: Build Windows (GUI) — onefile
        shell: pwsh
        run: |
          $version   = "${{ needs.build.outputs.version }}"; if ([string]::IsNullOrWhiteSpace($version)) { $version = "0.0.0" }
          $exeName   = "IoC-Scanner_Windows_v$version"
          "WINDOWS_GUI_EXE=$exeName.exe" >> $env:GITHUB_ENV
          $entryPath = (Resolve-Path "entry_gui.py").Path

          $args = @(
            "--noconfirm","--onefile","--clean","--noupx",
            "--windowed",
            "--name",$exeName,
            "--add-data","scanner\assets\icon.ico;assets",
            "--add-data","scanner\assets\icon.png;assets",
            "--version-file","build-res\file_version.txt",
            "--manifest","build-res\app.manifest"
          )

          if (Test-Path "scanner\assets\icon.ico") {
            $args += @("--icon","scanner\assets\icon.ico")
          }

          & pyinstaller @args $entryPath

          if (!(Test-Path "dist\$exeName.exe")) {
            Write-Error "EXE GUI manquant"; exit 1
          } else {
            Write-Host "✅ EXE généré: dist\$exeName.exe"
          }

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: dist/${{ env.WINDOWS_GUI_EXE }}
          if-no-files-found: error
          retention-days: 7

  Linux_Standalone_Build:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install system deps (Tk) + PyInstaller
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk tk
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && python -m pip install -r requirements.txt || true
          python -m pip install "pyinstaller>=6.0"
          pyinstaller --version

      - name: Create entrypoint (GUI only)
        run: |
          cat > entry_gui.py << 'PY'
          from scanner.gui import launch_gui
          if __name__ == "__main__":
              launch_gui()
          PY

      - name: Build Linux Standalone (GUI)
        env:
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          set -e
          version="${VERSION:-0.0.0}"
          exeName="IoC-Scanner_Linux_v${version}"
          echo "LINUX_GUI_BIN=${exeName}" >> $GITHUB_ENV
          ARGS=( --noconfirm --clean --noupx --onefile --windowed --name "$exeName" )
          if [ -f "scanner/assets/icon.png" ]; then
            ARGS+=( --icon scanner/assets/icon.png --add-data "scanner/assets/icon.png:assets" )
          fi
                    
          pyinstaller "${ARGS[@]}" entry_gui.py
          [ -f "dist/$exeName" ]

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-bin
          path: dist/${{ env.LINUX_GUI_BIN }}
          if-no-files-found: error
          retention-days: 7

  macOS_Standalone_Build:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: macos-latest
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python deps (+ PyInstaller)
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && python -m pip install -r requirements.txt || true
          python -m pip install "pyinstaller>=6.0"
          pyinstaller --version

      - name: Create entrypoint (GUI only)
        run: |
          cat > entry_gui.py << 'PY'
          from scanner.gui import launch_gui
          if __name__ == "__main__":
              launch_gui()
          PY

      # Génère un .icns valide depuis le PNG
      - name: Generate scanner/assets/icon.icns from scanner/assets/icon.png
        run: |
          set -e
          if [ ! -f "scanner/assets/icon.png" ]; then
            echo "❌ scanner/assets/icon.png introuvable. Ajoute un PNG source."
            exit 1
          fi
          rm -f scanner/assets/icon.icns
          rm -rf scanner/assets/icon.iconset
          mkdir -p scanner/assets/icon.iconset
          for size in 16 32 64 128 256 512; do
            sips -z $size $size scanner/assets/icon.png --out scanner/assets/icon.iconset/icon_${size}x${size}.png > /dev/null
            dbl=$((size*2))
            sips -z $dbl $dbl scanner/assets/icon.png --out scanner/assets/icon.iconset/icon_${size}x${size}@2x.png > /dev/null
          done
          iconutil -c icns scanner/assets/icon.iconset -o scanner/assets/icon.icns
          ls -lh scanner/assets/icon.icns

      - name: Build macOS (GUI)
        env:
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          set -e
          version="${VERSION:-0.0.0}"
          exeName="IoC-Scanner_macOS_v${version}"
          echo "MAC_GUI_BIN=${exeName}" >> $GITHUB_ENV
          ARGS=( --noconfirm --clean --noupx --onefile --windowed --name "$exeName" )
          ARGS+=( --icon "scanner/assets/icon.icns" )
          ARGS+=( --add-data "scanner/assets/icon.png:assets" )
                    
          pyinstaller "${ARGS[@]}" entry_gui.py
          [ -f "dist/$exeName" ]

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/${{ env.MAC_GUI_BIN }}
          if-no-files-found: error
          retention-days: 7

  release:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: ubuntu-latest
    needs: [ build, Windows_Standalone_Build, Linux_Standalone_Build, macOS_Standalone_Build ]
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-bin
          path: dist/

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-bin
          path: dist/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-app
          path: dist/

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          name: IoC-Scanner v${{ needs.build.outputs.version }}
          body: |
            GUI uniquement (Windows / Linux / macOS).
            - Windows: onefile, manifest & version info, icône depuis scanner\assets\icon.ico, pas d'UPX.
            - Linux:   onefile, icône PNG si présente.
            - macOS:   onefile, icône .icns générée depuis PNG.
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
