name: Build and Release (Windows + Linux + macOS Standalone)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.compare.outputs.greater }}
      version: ${{ steps.read_version.outputs.version }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Dernière release → version numérique (retire préfixe type "v")
      - name: Get latest release tag
        id: latest
        run: |
          set -e
          TOKEN="${{ secrets.TOKEN }}"
          if [ -z "$TOKEN" ]; then TOKEN="${{ secrets.GITHUB_TOKEN }}"; fi

          LATEST_TAG=$(curl -s -H "Authorization: token ${TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name // empty')

          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then LATEST_TAG="0.0.0"; fi
          LATEST_VERSION=$(printf "%s" "$LATEST_TAG" | sed -E 's/^[^0-9]*//')

          echo "LATEST_TAG=$LATEST_TAG"           >> $GITHUB_ENV
          echo "LATEST_VERSION=$LATEST_VERSION"   >> $GITHUB_ENV
          echo "LATEST_VERSION=$LATEST_VERSION"

      # Lit version.txt (ligne 1) et nettoie
      - name: Read version.txt
        id: read_version
        run: |
          set -e
          [ -f version.txt ] || { echo "version.txt introuvable à la racine"; exit 1; }
          RAW_VERSION=$(head -n1 version.txt | tr -d '\r' | xargs)
          [ -n "$RAW_VERSION" ] || { echo "version.txt est vide"; exit 1; }
          VERSION=$(printf "%s" "$RAW_VERSION" | sed -E 's/^[^0-9]*//')

          echo "VERSION=$VERSION"         >> $GITHUB_ENV
          echo "version=$VERSION"         >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"

      # Compare version fichier vs dernière release
      - name: Compare versions
        id: compare
        run: |
          echo "Comparaison: NEW=${{ env.VERSION }} ; LATEST=${{ env.LATEST_VERSION }}"
          if dpkg --compare-versions "${{ env.VERSION }}" gt "${{ env.LATEST_VERSION }}"; then
            echo "greater=true"  >> $GITHUB_OUTPUT
            echo "GREATER=true"  >> $GITHUB_ENV
            echo "Nouvelle version détectée"
          else
            echo "greater=false" >> $GITHUB_OUTPUT
            echo "GREATER=false" >> $GITHUB_ENV
            echo "Pas de bump de version"
          fi

      # Tag à créer/mettre à jour (softprops créera le tag s'il n'existe pas)
      - name: Compute tag
        id: tag
        run: |
          echo "tag=v${{ env.VERSION }}" >> $GITHUB_OUTPUT

  Windows_Standalone_Build:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: windows-latest
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install deps (PyInstaller + project)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") {
            python -m pip install -r requirements.txt
          }
          python -m pip install "pyinstaller>=6.0"
          pyinstaller --version

      - name: Create entrypoints (CLI & GUI)
        shell: pwsh
        run: |
          Set-Content entry_cli.py @"
          from scanner.cli import main
          if __name__ == "__main__":
              main()
          "@
                    Set-Content entry_gui.py @"
          from scanner.gui import launch_gui
          if __name__ == "__main__":
              launch_gui()
          "@

      - name: Build Windows Standalone (CLI)
        shell: pwsh
        run: |
          $version = "${{ needs.build.outputs.version }}"
          if ([string]::IsNullOrWhiteSpace($version)) { $version = "0.0.0" }
          $exeName = "IoCScanner_CLI_Windows_v$version"
          "WINDOWS_CLI_EXE=$exeName.exe" >> $env:GITHUB_ENV
          pyinstaller --noconfirm --onefile --console --name $exeName entry_cli.py
          if (!(Test-Path "dist\$exeName.exe")) { Write-Error "EXE CLI manquant"; exit 1 }

      - name: Build Windows Standalone (GUI)
        shell: pwsh
        run: |
          $version = "${{ needs.build.outputs.version }}"
          if ([string]::IsNullOrWhiteSpace($version)) { $version = "0.0.0" }
          $exeName = "IoCScanner_GUI_Windows_v$version"
          "WINDOWS_GUI_EXE=$exeName.exe" >> $env:GITHUB_ENV
          pyinstaller --noconfirm --onefile --windowed --name $exeName entry_gui.py
          if (!(Test-Path "dist\$exeName.exe")) { Write-Error "EXE GUI manquant"; exit 1 }

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: |
            dist/${{ env.WINDOWS_CLI_EXE }}
            dist/${{ env.WINDOWS_GUI_EXE }}
          if-no-files-found: error
          retention-days: 7

  Linux_Standalone_Build:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install system deps (Tk) + PyInstaller
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk tk
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && python -m pip install -r requirements.txt || true
          python -m pip install "pyinstaller>=6.0"
          pyinstaller --version

      - name: Create entrypoints (CLI & GUI)
        run: |
          cat > entry_cli.py << 'PY'
          from scanner.cli import main
          if __name__ == "__main__":
              main()
          PY
                    cat > entry_gui.py << 'PY'
          from scanner.gui import launch_gui
          if __name__ == "__main__":
              launch_gui()
          PY

      - name: Build Linux Standalone (CLI)
        env:
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          set -e
          version="${VERSION:-0.0.0}"
          exeName="IoCScanner_CLI_Linux_v${version}"
          echo "LINUX_CLI_BIN=${exeName}" >> $GITHUB_ENV
          pyinstaller --noconfirm --onefile --console --name "$exeName" entry_cli.py
          [ -f "dist/$exeName" ]

      - name: Build Linux Standalone (GUI)
        env:
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          set -e
          version="${VERSION:-0.0.0}"
          exeName="IoCScanner_GUI_Linux_v${version}"
          echo "LINUX_GUI_BIN=${exeName}" >> $GITHUB_ENV
          pyinstaller --noconfirm --onefile --windowed --name "$exeName" entry_gui.py
          [ -f "dist/$exeName" ]

      - name: Archive Linux binaries
        run: |
          tar -C dist -czf dist/IoCScanner_Linux_binaries.tar.gz \
            "${LINUX_CLI_BIN}" "${LINUX_GUI_BIN}"

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-bin
          path: dist/IoCScanner_Linux_binaries.tar.gz
          if-no-files-found: error
          retention-days: 7

  macOS_Standalone_Build:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: macos-latest
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python deps (+ PyInstaller)
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && python -m pip install -r requirements.txt || true
          python -m pip install "pyinstaller>=6.0"
          pyinstaller --version

      - name: Create entrypoints (CLI & GUI)
        run: |
          cat > entry_cli.py << 'PY'
          from scanner.cli import main
          if __name__ == "__main__":
              main()
          PY
                    cat > entry_gui.py << 'PY'
          from scanner.gui import launch_gui
          if __name__ == "__main__":
              launch_gui()
          PY

      - name: Build macOS (CLI)
        env:
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          set -e
          version="${VERSION:-0.0.0}"
          exeName="IoCScanner_CLI_macOS_v${version}"
          echo "MAC_CLI_BIN=${exeName}" >> $GITHUB_ENV
          pyinstaller --noconfirm --onefile --console --name "$exeName" entry_cli.py
          [ -f "dist/$exeName" ]

      - name: Build macOS (GUI)
        env:
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          set -e
          version="${VERSION:-0.0.0}"
          exeName="IoCScanner_GUI_macOS_v${version}"
          echo "MAC_GUI_BIN=${exeName}" >> $GITHUB_ENV
          pyinstaller --noconfirm --onefile --windowed --name "$exeName" entry_gui.py
          [ -f "dist/$exeName" ]

      - name: Zip macOS binaries
        run: |
          cd dist && /usr/bin/zip -r IoCScanner_macOS_binaries.zip \
            "${MAC_CLI_BIN}" "${MAC_GUI_BIN}"

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/IoCScanner_macOS_binaries.zip
          if-no-files-found: error
          retention-days: 7

  release:
    if: ${{ needs.build.outputs.should_release == 'true' }}
    runs-on: ubuntu-latest
    needs: [ build, Windows_Standalone_Build, Linux_Standalone_Build, macOS_Standalone_Build ]
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-bin
          path: dist/

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-bin
          path: dist/

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-app
          path: dist/

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          name: IoC-Scanner v${{ needs.build.outputs.version }}
          body: Windows, Linux & macOS standalone builds
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}
